name: Mirror Server to Private Repo

on:
  push:
    branches:
      - main

jobs:
  sync_graphic:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Server Repository
      uses: actions/checkout@v3

    - name: Install jq
      run: sudo apt-get install -y jq

    - name: Trigger Jenkins Build
      env:
        JENKINS_URL: ${{ secrets.JENKINS_URL }}
        JENKINS_USER: ${{ secrets.JENKINS_USER }}
        JENKINS_API_TOKEN: ${{ secrets.JENKINS_API_TOKEN }}
        JENKINS_JOB_NAME: ${{ secrets.JENKINS_JOB_NAME }}
      run: |
        build_url="${JENKINS_URL}${JENKINS_JOB_NAME}/build"
        job_response=$(curl -s -X POST "$build_url" --user ${JENKINS_USER}:${JENKINS_API_TOKEN})

        sleep 10

        last_build_number=$(curl -s "${JENKINS_URL}${JENKINS_JOB_NAME}/lastBuild/buildNumber" --user ${JENKINS_USER}:${JENKINS_API_TOKEN})

        while true; do
          build_status=$(curl -s "${JENKINS_URL}${JENKINS_JOB_NAME}/${last_build_number}/api/json" --user ${JENKINS_USER}:${JENKINS_API_TOKEN} | jq -r '.result')
          if [ "$build_status" == "SUCCESS" ]; then
            echo "Build succeeded."
            echo "::set-output name=build_status::SUCCESS"
            exit 0
          elif [ "$build_status" == "FAILURE" ]; then
            echo "::set-output name=build_status::FAILURE"
            echo "Build failed."
            exit 1
          elif [ "$build_status" == "ABORTED" ]; then
            echo "Build was aborted."
            echo "::set-output name=build_status::ABORTED"
            exit 1
          elif [ "$build_status" == "null" ]; then
            echo "Build is still running..."
          else
            echo "Unknown build status: $build_status"
            echo "::set-output name=build_status::UNKNOWN"
            exit 1
          fi
          sleep 10
        done



    - name: Sync with Private Repository
      if: steps.jenkins_build.outputs.build_status == 'SUCCESS'
      env:
        SSH_PRIVATE_KEY: ${{ secrets.POTAT_KEY }}
      run: |
        git config --global user.email "mathis.gheri@epitech.eu"
        git config --global user.name "MathisGheri"
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts

        # Clone the private repo
        git clone --depth 1 git@github.com:Potat-Gang-Corp/Zappy.git private-repo

        # Ensure the destination directory exists
        mkdir -p private-repo/Graphic

        # Copy server files to the Server directory in the private repo
        rsync -av --delete --exclude '.git' --exclude 'private-repo' --exclude '.github' . private-repo/Graphic/

        cd private-repo
        git add Graphic/
        git commit -m "[+] Sync Graphic repository with the final one"
        git push origin main