name: Mirror Server to Private Repo

on:
  push:
    branches:
      - main

jobs:
  sync_graphic:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Server Repository
      uses: actions/checkout@v3

    - name: Install jq
      run: sudo apt-get install -y jq

    - name: Trigger Jenkins Build
      env:
        JENKINS_URL: ${{ secrets.JENKINS_URL }}
        JENKINS_USER: ${{ secrets.JENKINS_USER }}
        JENKINS_API_TOKEN: 1155db0fa8072219ec71fcd65c5f207072
        JENKINS_JOB_NAME: "jenkins/job/Zappy/job/Graphic/job/Build_all/"
      run: |
        # Démarrer le job sans besoin de Crumb
        build_url="https://potatgangcorp.fr/${JENKINS_JOB_NAME}/build"
        job_response=$(curl -s -X POST "$build_url" --user ${JENKINS_USER}:${JENKINS_API_TOKEN})
        echo "Job started: $job_response"

        # Attendre quelques secondes pour permettre à Jenkins de démarrer le job et obtenir le numéro de build
        sleep 10

        # Obtenir le numéro du dernier build
        last_build_number=$(curl -s "https://potatgangcorp.fr/${JENKINS_JOB_NAME}/lastBuild/buildNumber" --user ${JENKINS_USER}:${JENKINS_API_TOKEN})
        echo "Last build number: $last_build_number"

        # Fonction pour vérifier le statut du build
        check_build_status() {
          build_status=$(curl -s "https://potatgangcorp.fr/${JENKINS_JOB_NAME}/${last_build_number}/api/json" --user ${JENKINS_USER}:${JENKINS_API_TOKEN} | jq -r '.result')
          echo "Build status: $build_status"
          echo $build_status
        }

        # Boucle pour vérifier le statut du build jusqu'à ce qu'il soit terminé
        while true; do
          status=$(check_build_status)
          if [ "$status" == "SUCCESS" ]; then
            echo "Build succeeded."
            exit 0
          elif [ "$status" == "FAILURE" ]; then
            echo "Build failed."
            exit 1
          elif [ "$status" == "ABORTED" ]; then
            echo "Build was aborted."
            exit 1
          elif [ "$status" == "null" ]; then
            echo "Build is still running..."
          else
            echo "Unknown build status: $status"
            exit 1
          fi
          sleep 10
        done



    - name: Sync with Private Repository
      env:
        SSH_PRIVATE_KEY: ${{ secrets.POTAT_KEY }}
      run: |
        git config --global user.email "mathis.gheri@epitech.eu"
        git config --global user.name "MathisGheri"
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts

        # Clone the private repo
        git clone --depth 1 git@github.com:Potat-Gang-Corp/Zappy.git private-repo

        # Ensure the destination directory exists
        mkdir -p private-repo/Graphic

        # Copy server files to the Server directory in the private repo
        rsync -av --delete --exclude '.git' --exclude 'private-repo' --exclude '.github' . private-repo/Graphic/

        cd private-repo
        git add Graphic/
        git commit -m "[+] Sync Graphic repository with the final one"
        git push origin main